name: confirm_corek8s

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

  workflow_dispatch:

jobs:
  confirm_corek8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout instant
        uses: actions/checkout@v2
        with:
          repository: openhie/instant
          ref: '0.0.5'

      - run: ls -la

      - name: Prepare instant
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: npm install -g yarn

      - run: yarn install

      # create kind cluster if using act
      - uses: engineerd/setup-kind@v0.5.0
        # if: ${{ env.ACT }}
        with:
          # if a recent version is not used, there are many failures in the cluster
          version: "v0.11.1"

      # have to add kubectl if using act as the runner bc its missing, not req for github actions workers
      - name: Add kubectl if act is being used
        if: ${{ env.ACT }}
        # if: ${{ !env.ACT }}
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      # create minikube cluster if not using act
      # instant may assume this it is local bc minikube, so try leaving it out
      # - name: start minikube 
      #   if: ${{ !env.ACT }}
      #   id: minikube
      #   uses: medyagh/setup-minikube@master

      - name: Testing
        run: |
          kubectl version  --short | grep -i server
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}

      - name: Launch Core
        # this fails due to a mounting issue:
        # The path /root/.minikube is not shared from the host and is not known to Docker
        # run: yarn docker:instant init -t k8s core
        # use main script directly
        # must be in work dir needed for the main/k8s script to run correctly
        working-directory: core/kubernetes
        run: bash main/k8s.sh init
        # allow for troubleshooting
        # continue-on-error: true

      # wait for instant core to come up
      - run: sleep 240

      - name: Curl Capability Statement
        run: curl -s 'http://localhost:31313/fhir/metadata' | jq . > capabilitystatement.json
        continue-on-error: true

      - name: Store Capability Statement
        uses: actions/upload-artifact@v2
        if: ${{ !env.ACT }}
        with:
          name: capabilitystatement.json
          path: capabilitystatement.json
        continue-on-error: true

      - name: Teardown Core
        # this fails due to a mounting issue:
        # The path /root/.minikube is not shared from the host and is not known to Docker
        # run: yarn docker:instant init -t k8s core
        # use main script directly
        # must be in work dir needed for the main/k8s script to run correctly
        working-directory: core/kubernetes
        run: bash main/k8s.sh destroy
        # allow for troubleshooting
        continue-on-error: true

      # cleanup if using act
      - name: Delete Kind cluster
        run: kind delete cluster
        # if: ${{ env.ACT }}

